Added ICCN chunk index and parsed through document to add references to ICCN
w3c/PNG-spec pull request #117
Opened 2022-04-18 19:26 UTC by digitaltvguy

Updated index.html to allow merge (edited wrong version so had to back up and re-submit)

Added ICCN chunk index and parsed through document to add references to ICCN.

A few fixes to cICP.

2022-04-20 05:06 UTC, ProgramMax requested changes
A few changes need to be made.
Also, there are links to the fragment #iccn-embedded-icc-profile but no element has an ID of iccn-embedded-icc-profile.

2022-04-20 05:06 UTC, ProgramMax commented on index.html
> +"#iccp-embedded-icc-profile"><span class="chunk">iCCP</span></a>, "#iccn-embedded-icc-profile">
This seems to be missing < a href=

2022-04-20 05:06 UTC, ProgramMax commented on index.html
> +all absent), standalone image viewers should choose
This mentions iCCP twice. It is probably supposed to be iCCN.

2022-04-20 05:07 UTC, ProgramMax commented
I should mention: Because I updated your pull request, you might need to $git pull before you make your changes.

2022-05-02 14:15 UTC, svgeesus commented on index.html
> +    Latin-1 characters, spaces and includes UTF-8 characters.  Leading, trailing,
Yes, just say "printable characters"

2022-05-02 18:26 UTC, svgeesus commented on index.html
> +    Embedded ICC Profiles v4 and UTF-8 Profile Names</h2>
Change "Embedded ICC Profiles v4 and UTF-8 Profile Names" to "Embedded ICC.2 Profiles [[ICC-2]][[ISO 20677-1]] and UTF-8 Profile Names"

2022-05-02 18:26 UTC, svgeesus commented on index.html
> +    <p>PNG files should not simultaneously contain embedded iCCP and iCCN tags.</p>
Is that still true? It is now possible to put an ICC.2 (iccMax) profile into iCCN and an older ICC.1 profile into iCCP. So I suggest dropping this paragraph.

2022-05-02 18:26 UTC, svgeesus commented on index.html
> +  "chunk">iCCN</span></a>, <a href="#sbit-significant-bits"><span class=
As discussed on the call today, all instances of `iCCN` should now be changed to `iCCM` and similarly, to not break links, change all "iccn-embedded-icc-profile" to "iccm-embedded-icc-profile"

2022-05-30 22:06 UTC, closed without merging