Closes: Example 14 talks about minimum luminance in the max luminance section #263
w3c/PNG-spec pull request #267
Opened 2023-02-17 20:49 UTC by digitaltvguy

Fixed descriptions of MaxCLL and MaxFall

2023-02-17 23:25 UTC, ProgramMax commented
This pull request seems to be your previous changes + the new change.
I think you meant for the pull request to only include https://github.com/w3c/PNG-spec/pull/267/commits/5cf95d731ee4228ee6cdb16b152c85d95c9a9915

Some existing fixes are causing a conflict in this pull request.

I'll see if the conflicts can be resolved easily so we can squash this pull request and merge.

2023-02-17 23:44 UTC, ProgramMax requested changes
LGTM.
Except while resolving conflicts, I accidentally left in something we don't want to change.

Can you accept the suggested change?
Then I can approve the pull request.

2023-02-17 23:44 UTC, ProgramMax commented on index.html
> +                <td>0.0005 cd/m<sup>2</sup></td>
```suggestion
                <td>0.005 cd/m<sup>2</sup></td>
```

Oops.
I was able to resolve the conflicts and make this pull request clean.
However, I missed this line.
This should be 0.005, not 0.0005.

2023-02-18 14:09 UTC, digitaltvguy commented
Please recheck my change.  I also updated example in mDCv to show SDR display @ 203cd/m2 instead of 200 (which matches ITU BT.2408-6 pending annex).

2023-02-18 14:39 UTC, ProgramMax approved these changes
LGTM

Although, it looks like the 203 cd/m^2 change didn't get in somehow?
But we can add that in a separate pull request. This pull request is ready to go as-is.

2023-02-18 16:17 UTC, merged