Added unsigned integer examples for cICp Chunk
w3c/PNG-spec pull request #383
Opened 2023-12-08 14:58 UTC by digitaltvguy

This addresses some confusion we had while building the conformance files for cICp and removes the sRGB example that was unnecessary (it duplicates functions already existing in PNG)

2023-12-10 23:03 UTC, svgeesus requested changes

2023-12-10 23:03 UTC, svgeesus commented on index.html
> +          <p>The cICp chunk consists of four 1-byte unsigned integers to identify the characterstics described above.</p>
Captial P

2023-12-11 14:05 UTC, svgeesus commented on index.html
> +          <p>The cICp chunk consists of four 1-byte unsigned integers to identify the characterstics described above.</p>
```suggestion
          <p>The cICP chunk consists of four 1-byte unsigned integers to identify the characteristics described above.</p>
```

2023-12-11 14:06 UTC, merged

2023-12-11 15:42 UTC, chrisn commented on index.html
> +9 16 0 1 (Decimal)
I filed a follow up PR, https://github.com/w3c/PNG-spec/pull/393.